name: Conftest
on: [pull_request]

jobs:
  conftest:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Exec conftest
      uses: instrumenta/conftest-action@master
      with:
        files: resources
        policy: policy
        namespace: main
