name: Conftest unit testing and verification for itself
on: [pull_request]

jobs:
  unit_testing:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup node
      uses: actions/setup-node@v2
    - name: Install conftest
      run: |
        wget https://github.com/open-policy-agent/conftest/releases/download/v0.24.0/conftest_0.24.0_Linux_x86_64.tar.gz
        tar xzf conftest_0.24.0_Linux_x86_64.tar.gz
        sudo mv conftest /usr/local/bin
    - name: Conftest unit testing
      run: |
        conftest verify policy
        echo $0
  verification:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup node
      uses: actions/setup-node@v2
    - name: Install conftest
      run: |
        wget https://github.com/open-policy-agent/conftest/releases/download/v0.24.0/conftest_0.24.0_Linux_x86_64.tar.gz
        tar xzf conftest_0.24.0_Linux_x86_64.tar.gz
        sudo mv conftest /usr/local/bin
      run: |
        conftest test resources --policy policy --all-namespaces
        echo $0
