name: Conftest
on: [pull_request]

jobs:
  conftest:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Exec conftest
      uses: YubicoLabs/action-conftest@v2
      with:
        files: resources
